name: Build the openfast image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image for multiple architectures
        run: docker buildx build --push --tag octue/openfast:latest .
